# Generated by Django 3.2.7 on 2022-05-15 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tokoh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=100)),
                ('jenis_kelamin', models.CharField(choices=[('Laki-laki', 'Laki-laki'), ('Perempuan', 'Perempuan')], default='Perempuan', max_length=9)),
                ('warna_kulit', models.CharField(choices=[('#f0067e', '#f0067e'), ('#fa1ec8', '#fa1ec8'), ('#a823d2', '#a823d2'), ('#afa825', '#afa825')], default='#f0067e', max_length=7)),
                ('pekerjaan', models.CharField(choices=[('Pelukis ', 'Pelukis'), ('Programmer', 'Programmer'), ('Komedian', 'Komedian'), ('Businessman', 'Businessman'), ('Atlet', 'Atlet')], default='Pelukis', max_length=11)),
            ],
        ),
    ]
