# Generated by Django 3.2.7 on 2022-05-25 21:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tokoh', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tokoh',
        ),
    ]
